on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build Contentless
      - name: Build test project
        run: |
          dotnet restore Test
          dotnet run --project Contentless Test/Content/Content.mgcb Test/Test.csproj
          dotnet build Test